
<div class="col-md-6">
    <form class="w-100" action="<?= $this->getUrl('/system/module/addcontroller') ?>" method="POST">
    	<div class="card">
    		<div class="card-body">
    			<h5 class="card-title m-b-15">Add Controller</h5>

                <input type="hidden" name="vendor_name" value="<?= $vendorName ?>" required>
                <input type="hidden" name="module_name" value="<?= $moduleName ?>" required>

                <div class="form-group row">
                    <label class="col-sm-3 text-right control-label col-form-label">Controller For</label>
                    <div class="col-md-9">
                        <select class="select2 form-control custom-select" name="controller_type" style="width: 100%; height:36px;">
                            <option value="public">Public</option>
                            <option value="admin">Admin</option>
                        </select>
                    </div>
                </div>

    			<div class="form-group row">
                    <label for="controller-route" class="col-sm-3 text-right control-label col-form-label">Route</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="controller-route" name="controller_route" value="">
                        <p class="m-b-0"><small class="text-muted">Default is index</small></p>
                    </div>
                </div>

    			<div class="form-group row">
                    <label for="controller-controller" class="col-sm-3 text-right control-label col-form-label">Controller</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="controller-controller" name="controller_controller" value="">
                        <p class="m-b-0"><small class="text-muted">Default is index</small></p>
                    </div>
                </div>

    			<div class="form-group row">
                    <label for="" class="col-sm-3 text-right control-label col-form-label">Action</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="controller-action" name="controller_action" value="">
                        <p class="m-b-0"><small class="text-muted">Default is index</small></p>
                    </div>
                </div>
    		</div>
            <div class="border-top">
                <div class="card-body">
                    <button class="btn btn-primary" name="save" value="save">Save</button>
                </div>
            </div>
    	</div>
    </form>
</div>
