<?php
/**
* Copyright 2018 Opoink Framework (http://opoink.com/)
* Licensed under MIT, see LICENSE.md
*/
?>
<div class="card">
	<div class="card-body vue-comp-schema">
		<h5 class="card-title m-b-15">Database</h5>
  		<my-button :schema="schema"></my-button>
  		<my-testing :testing="testing" :schema="schema"></my-testing>
	</div>
    <div class="border-top">
        <div class="card-body">
            <button class="btn btn-primary" name="save" value="save">Add Schema</button>
        </div>
    </div>
</div>