<?php
/**
* Copyright 2018 Opoink Framework (http://opoink.com/)
* Licensed under MIT, see LICENSE.md
*/
?>

<!DOCTYPE html>
<html dir="ltr" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" sizes="16x16" href="/public/sys/assets/images/favicon.ico">
        <title><?= $this->pageTitle ?></title>

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		
        <link href="<?= $this->getUrl('/system/static/css/style.css') ?>" rel="stylesheet">
        <link href="/public/sys/dist/css/icons/font-awesome/css/fontawesome-all.min.css" rel="stylesheet">
	</head>
    <body>
        <div id="app-root">
			<router-view></router-view>
			<!-- <sidenav-component></sidenav-component>
			<div class="container-wrapper">
				<main-header-component></main-header-component>
				<router-view></router-view>
			</div> -->
			<toast-component></toast-component>
		</div>
		
		<script src="/public/sys/dist/js/jquery.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
		<script src="/public/sys/dist/js/vue.js"></script>
		<script src="/public/sys/dist/js/vue-router.js"></script>
		
        <script src="<?= $this->getUrl('/system/static/vue/main.js') ?>"></script>
    </body>
</html>