<!DOCTYPE html>
<html dir="ltr">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" sizes="16x16" href="/public/sys/assets/images/favicon.ico">
	<title>Error: <?= $code ?> <?= $title ?></title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	
	<link href="<?= $this->getUrl('/system/static/css/style.css') ?>" rel="stylesheet">
	<link href="/public/sys/dist/css/icons/font-awesome/css/fontawesome-all.min.css" rel="stylesheet">
</head>

<body class="opoink-error-page">
    <div class="main-wrapper">
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <div class="error-box">
            <?= $template ?>
        </div>
    </div>
</body>

</html>