<?php
/**
* Copyright 2018 Opoink Framework (http://opoink.com/)
* Licensed under MIT, see LICENSE.md
*/
?>	
<style type="text/css">
.error-info-container {
	position: fixed;
	bottom: 0px;
	left: 0px;
	z-index: 9999999999;
	width: 100%;
	height: 350px;
	padding: 15px;
	background: rgba(0,0,0,0.5);
	overflow: auto;
	font-family: sans-serif;
}
.error-container {
	max-width: 1299px;
	width: 100%;
	margin-left: auto;
	margin-right: auto;
}
.error-info h4 {
	text-align: center;
	color: red;
	margin: 0px 0px 20px 0px;
	font-size: 28px;
}
.error-info p {
	color: #ffffff;
	margin: 0;
}
.error-info,
.main-error-target {
	background: #141619;
	margin: 15px 0px;
	padding: 15px;
	border-radius: 10px;
}
.main-error-target p {
	margin: 0;
	color: #ffffff;
}
.main-error-target p.active {
	background: #1F262D;
	padding: 5px;
}

.trace-box {
	display: block;
	padding: 9.5px;
	margin: 0 0 10px;
	font-size: 13px;
	line-height: 1.42857143;
	color: #333;
	word-break: break-all;
	word-wrap: break-word;
	background-color: #f5f5f5;
	border: 1px solid #ccc;
	border-radius: 4px;
}
.trace-key {
	color: #333;
}
.trace-var-str {
	color: #cc0000;
}
.trace-var-int {
	color: #4e9a06;
}
</style>


<div class="error-info-container">
	<div class="error-container">
		<div class="">
			<div class="error-info">
				<h4>Error occurred:</h4>
				<p>This error will trace will only show during development mode. You can check the logs, if in production mode.</p>
				<br><br>
				<p>Type: <?= get_class($e) ?></p>
				<p>Message: <?= $e->getMessage() ?></p>
				<p>File: <?= $e->getFile() ?></p>
				<p>Line: <?= $e->getLine() ?></p>
			</div>
			<div class="main-error-target">
				<?php
					foreach($fileData as $key => $line) {
						$l = $key + 1;
						if($l >= $firstLine && $l <= $lastLine){
							if($l == $e->getLine()){
								echo '<p class=" active">' . $l . ': ' . htmlentities($line) . '</p>';
							} else {
								echo '<p class="">' . $l . ': ' . htmlentities($line) . '</p>';
							}
						}
						if($l == $lastLine) {
							break;
						}
					}
				?>
			</div>
			<div class="error-info">
				<h4>Trace: </h4>
				<?php foreach($e->getTrace() as $trace): ?>
					<div class="trace-box">
						<?php
						$t = '';
						foreach($trace as $key => $val){
							if(is_string($val) || is_integer($val)) {
								$t .= '<p><span class="trace-key"># ';
								$t .= $key . ':</span> ';
								if(is_integer($val)){
									$t .= '<span class="trace-var-int">'.$val.'</span>';
								} else {
									$t .= '<span class="trace-var-str">'.$val.'</span>';
								}
							}
						}
						$t .= '</p>';
						echo $t;
						?>
					</div>	
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</div>